version: 0.2

      
phases:
  install:
    runtime-versions:
      java: corretto8

    commands:
      - echo install
  pre_build:
    commands:
      - echo pre-build
      - command
  build:
    commands:
      - echo build
      - mvn package
  post_build:
    commands:
      - echo post build

artifacts:
  files:
    - target\aws-cicd-pipeline-test-0.0.1-SNAPSHOT.jar
  
 